### ISSUE TITLE
smtpd_test.go:504

### ISSUE THREAD

**Issue by gertcuykens** [lavab/smtpd#3]
Hmm I think `go test -v` should not fail here?
```
=== RUN   TestInvalidListenAddress
--- FAIL: TestInvalidListenAddress (0.00s)
        smtpd_test.go:504: Unexpected port binding: listen tcp: address pleasedontwork: missing
port in address
```

**Comment by pzduniak** [comment]
1) Use https://github.com/pgpst/smtpd
2) Sounds like that's the case, IIRC the errors matched by type, so
something must have been changed in the stdlib.

**Comment by pzduniak** [comment]
Other than that the library could be maintained again soon(tm), we're
awaiting responses from accelerators regarding a project.

**Comment by gertcuykens** [comment]
Printed the error message, stdlib has changed it to this

```
--- FAIL: TestInvalidListenAddress (0.00s)
        smtpd_test.go:503: listen tcp: address pleasedontwork: missing port in address
        smtpd_test.go:505: Unexpected port binding: listen tcp: address pleasedontwork: missing
port in address
```

**Comment by pzduniak** [comment]
Just replace the equality sign with strings.Contains and it should work.

**Comment by gertcuykens** [comment]
Prefer this solution to be consistent with the other tests. Let me know when and where this repo will be maintained so I can rely on `go get -u` thanks

```go
func TestInvalidListenAddress(t *testing.T) {
	server := &smtpd.Server{}

	err := server.ListenAndServe("pleasedontwork")
	if err.Error() != "listen tcp: address pleasedontwork: missing port in address" {
		t.Fatalf("Unexpected port binding: %s", err)
	}
}
```

**Comment by gertcuykens** [comment]
closing this and opened pull request at https://github.com/pgpst/smtpd/pull/1
